### ISSUE TITLE
Cursor barley readable in edit mode

### ISSUE THREAD

**Issue by sceptiq** [Teyler7/dracula-typora-theme#3]
HI! 

would lave to use that theme... :) 

but im never able to locate my cursor 

<img width="1594" alt="whereiswally" src="https://github.com/Teyler7/dracula-typora-theme/assets/8125020/db6b3c2f-2cda-40cb-aa61-fcea98518f33">

he is behind the second dot :P

**Comment by MC-dusk** [comment]
Same problem. I tried searching "cursor" but not sure which one should be modified.

**Comment by Teyler7** [comment]
Hey @sceptiq. Thanks for creating the issue.

Yeah it was a bit tricky. Not very straightforward. It seems to be a border left to simulate a cursor in the mermaid context.

```css
/* Cursor color in Mermaid context */
pre.md-fences[lang="mermaid"] .CodeMirror-cursor {
  border-left: 2px solid var(--text-color1 ) !important;
}
```
